[package]
name        = "flix-htmldoc"
description = "A Flix combinator library to generate HTML."
version     = "0.2.1"
flix        = "0.48.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/flix-rosetree"           = "0.2.0"
"github:stephentetley/flix-pretty"             = "0.7.0"

